queue_rules:
  - name: Agoric
    conditions:
      - base=Agoric

pull_request_rules:
  - name: automerge to main with label automerge and branch protection passing
    conditions:
      - "#approved-reviews-by>0"
      - base=Agoric
      - label=automerge
    actions:
      queue:
        name: Agoric
        method: squash
